# Use the official PostgreSQL 16 image from Docker Hub
FROM postgres:16-alpine

# Set default environment variables for PostgreSQL
ENV POSTGRES_DB=mydb
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword

# Optional: Expose the default PostgreSQL port
EXPOSE 5432